# 공통 설정

server:
  port: 5000

spring:
  # 데이터베이스 설정
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    # 카멜케이스 형식으로도 입력 가능 driverClassName
    url: jdbc:oracle:thin:@${db.host}:${db.port}:XE
    username: ${db.username}
    password: ${db.password}

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true #sql 보이게
        format_sql: true # 줄개행
        use_sql_comments: true #설명
    hibernate:
      ddl-auto: update # 배포할땐 바꾸기

  # 라이브 리로드 설정
  devtools:
    livereload:
      enabled: true

  # 정적 자원 설정(Css, JS, 이미지) - 코드 바꼈을때 바로 반영되도록
  web:
    resources:
      staticLocations: file:src/main/resources/static/

  # 파일 업로드 용량 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB  #전체 최대 용량
      file-size-threshold: 30MB # 메모리 초과 되면 임시 폴더에서 만들어짐

# 파일 업로드 경로 설정
file:
  upload:
    path: D:/uploads
    url: /upload/ # 정적 경로

# 로거 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace

